openapi: 3.0.0
info:
  title: API do Sistema Escolar
  version: 1.0.0
  description: Documentação da API para gerenciamento de presenças dos alunos.

servers:
  - url: http://localhost:8080

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/atividade/turma:
    post:
      summary: Cria uma nova atividade para uma turma específica
      description: Cria uma atividade para todos os alunos de uma turma (baseada em ano_turma e classe). É obrigatório anexar um arquivo (ex: PDF, TXT).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - descricao
                - data_atividade
                - ano_turma
                - classe
                - arquivo
              properties:
                descricao:
                  type: string
                  example: Redação sobre o meio ambiente
                data_atividade:
                  type: string
                  format: date
                  example: "2025-07-05"
                ano_turma:
                  type: integer
                  example: 2
                classe:
                  type: string
                  example: B
                arquivo:
                  type: string
                  format: binary
      responses:
        '201':
          description: Atividade criada com sucesso e associada aos alunos da turma
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Atividade criada e associada aos alunos da turma
                  atividade:
                    type: object
        '400':
          description: Campos obrigatórios ausentes
        '404':
          description: Nenhum aluno encontrado para esse ano e classe
        '500':
          description: Erro interno no servidor

  # ... e assim para os outros endpoints
