# Usa a imagem oficial do Node 24
#FROM node:24

# Diretório de trabalho dentro do container
#WORKDIR /app

# Copia os arquivos de dependências
#COPY package*.json ./

# Instala dependências globais e locais
#RUN npm install -g nodemon && npm install

# Copia o restante dos arquivos da aplicação
#COPY . .

# Expõe a porta que o app usa (exemplo 3000)
#EXPOSE 3000

#CMD ["npm", "run", "dev"]


# FROM node:24

# WORKDIR /usr/src/app

# COPY . .

# RUN npm install -g nodemon && npm install

# EXPOSE 3000

# CMD ["npm", "run", "dev"]

FROM node:24

WORKDIR /usr/src/app

# Copia só os arquivos de dependências
COPY package*.json ./

# Instala as dependências no container
RUN npm install -g nodemon && npm install

# Copia o restante do código
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
